nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
     - DEFAULT_HOST=default
nginx-always-ok:
  image: taopaic/nginx-always-ok
  environment:
     - VIRTUAL_HOST=default